language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "node"
after_script:
  - npm install -g coveralls
  - coveralls < coverage/lcov.info
